# Generated by Django 2.2 on 2019-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dans_password_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='private_key',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salt',
            field=models.TextField(default='barf'),
            preserve_default=False,
        ),
    ]
