# Generated by Django 2.2 on 2019-08-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dans_password_manager', '0003_auto_20190811_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
