# Generated by Django 2.2 on 2019-09-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dans_password_manager', '0004_userinfo_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
